name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Verify version matches tag
      run: |
        # Extract version from pyproject.toml
        PROJECT_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        # Extract version from git tag (remove 'v' prefix if present)
        TAG_VERSION=${GITHUB_REF#refs/tags/}
        TAG_VERSION=${TAG_VERSION#v}
        
        echo "Project version: $PROJECT_VERSION"
        echo "Tag version: $TAG_VERSION"
        
        if [ "$PROJECT_VERSION" != "$TAG_VERSION" ]; then
          echo "ERROR: Version mismatch between pyproject.toml ($PROJECT_VERSION) and git tag ($TAG_VERSION)"
          exit 1
        fi
        
    - name: Build package
      run: python -m build
      
    - name: Check package
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
        
    - name: Create GitHub release notes
      run: |
        echo "✅ Package successfully published to PyPI!"
        echo "📦 Install with: \`pip install invokeai-py-client==${{ github.ref_name }}\`"
        echo "🔗 PyPI page: https://pypi.org/project/invokeai-py-client/${{ github.ref_name }}/"
