name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (vX.Y.Z) to publish (optional when manually dispatching)'
        required: false

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag/version
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.tag }}" ]; then
            RAW_TAG="${{ inputs.tag }}"
          else
            RAW_TAG="${GITHUB_REF#refs/tags/}"
          fi
          RAW_TAG=${RAW_TAG#v}
          echo "tag=$RAW_TAG" >> $GITHUB_OUTPUT
          echo "Using tag version: $RAW_TAG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Verify version matches tag
        id: verify
        shell: bash
        run: |
          set -euo pipefail
          VERSION=$(python - <<'PY'
import tomllib, pathlib
print(tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']['version'])
PY
)
          echo "Project version: $VERSION"
          echo "Tag version: ${{ steps.meta.outputs.tag }}"
          test "$VERSION" = "${{ steps.meta.outputs.tag }}" || { echo "Version mismatch"; exit 1; }

      - name: Build distribution
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true

      - name: Summary
        run: |
          echo "Published invokeai-py-client ${{ steps.meta.outputs.tag }}"
