name: Lint (src only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pixi
        shell: bash
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH
          pixi --version

      - name: Lint library code with ruff (via Pixi)
        shell: bash
        run: |
          pixi run -e dev ruff --version
          # Lint only the library for critical errors/warnings
          pixi run -e dev ruff check src/ --select E,F
